version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: solid_example_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solid_example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - solid_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: solid_example_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - solid_network

volumes:
  postgres_data:

networks:
  solid_network:
    driver: bridge 